[package]
name = "chainmail"
version = "0.1.0"
authors = ["Pocket7878 <poketo7878@gmail.com>"]
description = "Strategy based authentication middleware for Iron framework"
license = "MIT/Apache-2.0"
repository = "https://github.com/pocket7878/chainmail"

[dependencies]
iron = "0.4.*"
